{ name = "hydra-sdk"
, dependencies =
  [ "aeson"
  , "aff"
  , "affjax"
  , "affjax-node"
  , "argonaut"
  , "arrays"
  , "avar"
  , "bifunctors"
  , "bytearrays"
  , "cardano-types"
  , "codec-aeson"
  , "control"
  , "datetime"
  , "debug"
  , "effect"
  , "either"
  , "errors"
  , "exceptions"
  , "foldable-traversable"
  , "foreign-object"
  , "formatters"
  , "http-methods"
  , "integers"
  , "js-date"
  , "maybe"
  , "monad-logger"
  , "mote"
  , "mote-testplan"
  , "newtype"
  , "node-buffer"
  , "node-child-process"
  , "node-fs"
  , "node-path"
  , "node-process"
  , "node-streams"
  , "optparse"
  , "ordered-collections"
  , "parsing"
  , "partial"
  , "plutus-types"
  , "posix-types"
  , "prelude"
  , "profunctor"
  , "quickcheck"
  , "record"
  , "record-extra"
  , "safely"
  , "spec"
  , "strings"
  , "tailrec"
  , "transformers"
  , "tuples"
  , "uint"
  , "uri"
  , "uuid"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
