{ name = "hydra-sdk-example-minimal"
, dependencies =
  [ "aeson"
  , "aff"
  , "aff-retry"
  , "arrays"
  , "avar"
  , "bytearrays"
  , "cardano-key-wallet"
  , "cardano-provider"
  , "cardano-transaction-lib"
  , "cardano-types"
  , "codec-aeson"
  , "console"
  , "datetime"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "hydra-sdk"
  , "maybe"
  , "monad-logger"
  , "mote"
  , "newtype"
  , "node-buffer"
  , "node-child-process"
  , "node-fs"
  , "node-fs-aff"
  , "node-path"
  , "node-process"
  , "ordered-collections"
  , "parallel"
  , "posix-types"
  , "prelude"
  , "profunctor-lenses"
  , "quickcheck"
  , "refs"
  , "spec"
  , "strings"
  , "transformers"
  , "tuples"
  , "uint"
  , "uuid"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "app/**/*.purs", "test/**/*.purs" ]
}
